name: 'Files Sync and Delete'
description: 'Synchronizes files across multiple repositories. A fork of "Files Sync" supporting deletion of files and folders.'
author: 'wadackel'
branding:
  color: white
  icon: git-pull-request

inputs:
  github_token:
    description: 'Personal Access Token to use to create file sync and PR. Required if `GITHUB_APP_*` is not specified.'
    required: true
  github_api_url:
    description: 'API URL of the GitHub server.'
    default: 'https://api.github.com'
  config_file:
    description: 'The path for the sync configuration file.'
    default: '.github/files-sync-config.yaml'
  gpg_username:
    description: 'The username to use for the signature'
    default: ''
  gpg_email:
    description: 'The email to use for the signature'
    default: ''
  gpg_private_key:
    description: 'The private key created for the user with the username and email provided'
    default: ''
  gpg_passphrase:
    description: 'The passphrase to read the key'
    default: ''

outputs:
  pull_request_urls:
    description: 'URL array of PRs created to synchronize files.'
  synced_files:
    description: 'An array of all synchronized file names.'

runs:
  using: 'node20'
  main: 'dist/index.js'
