// GENERATED CODE - DO NOT MODIFY BY HAND
// (Generated by 'scripts/generate-inputs.ts')
import * as core from '@actions/core';

const keys: [key: string, required: boolean][] = [
  ['github_token', true],
  ['github_api_url', true],
  ['config_file', true],
  ['gpg_name', false],
  ['gpg_email', false],
  ['gpg_private_key', false],
  ['gpg_passphrase', false],
];

export type Inputs = {
  github_token: string;
  github_api_url: string;
  config_file: string;
  gpg_name: string;
  gpg_email: string;
  gpg_private_key: string;
  gpg_passphrase: string;
};

export const getInputs = (): Inputs => {
  const inputs = Object.create(null);
  for (const [key, required] of keys) {
    const v = core.getInput(key, { required });
    inputs[key] = !required && v === '' ? null : v;
  }
  return inputs as Inputs;
};
