name: Lint Commit Messages

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  commitlint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3.5.3
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v5
